# Generated by Django 2.1 on 2020-06-09 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('listing', models.CharField(max_length=200)),
                ('listing_id', models.IntegerField()),
                ('office', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('payment', models.CharField(max_length=200)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
